### ISSUE TITLE
YOUR TWITTER APP'S CONSUMER KEY AND CONSUMER SECRET ARE PUBLICLY AVAILABLE

### ISSUE THREAD

**Issue by karuppiah7890** [madisonbullard/tweet-formatter#1]
I found them in this commit : https://github.com/madisonbullard/tweet-formatter/commit/eb2ced6a276dcef109f3601f5fefb2a2b7b59c2a

**Comment by madisonbullard** [comment]
Thank you for this service. I am aware and changed the credentials a while ago.
